### PR TITLE
client: raise with invalid credentials

### PR DESCRIPTION
**Pull request by sirupsen**
When your credentials are invalid, in lieu of the unhelpful exception:

```
NoMethodError: undefined method `[]' for nil:NilClass
```

Let's show the much more useful message:

```
KindleHighlights::Client::AuthenticationError: Unable to sign in, received error: 'Your email or password was incorrect. Please try again.'
```

I've kept this as generic as possible, as it may handle other errors than just invalid credentials (which is what I spent 20m debugging).

Tested locally by flipping to invalid credentials.

Thanks for maintaining the upstream @speric!

✨

### CODE REVIEW

**Comment by speric** [comment]
Thanks @Sirupsen! Let me test this out locally.

**Comment by sirupsen** [comment]
@speric did you have time to take a look? 🎉

**Comment by speric** [comment]
Yes! Merging now, I'll cut a release soon.

**Comment by sirupsen** [comment]
👍

**Comment by speric** [comment]
https://github.com/speric/kindle-highlights/releases/tag/v1.0.1
https://rubygems.org/gems/kindle-highlights/versions/1.0.1

Thank you! 🎉 👍

**Comment by sirupsen** [comment]
Thanks for this gem @speric :-) I'm using it to funnel single-word Kindle highlights of words that aren't in my active vocabulary into Airtable where I learn the words, and then sync them to my flash card deck!

**Pull request merged**
