### PR TITLE
fix captcha detection

### PR DESCRIPTION
**Pull request by jurvis**
See issue: #23

### CODE REVIEW

**Comment by rapcal** [comment]
+1

**Comment by kuiro5** [comment]
Were you able to get this working? I tested out this fix, it raises the proper error, but the link doesn't seem to point to a captcha to be resolved.

**Comment by speric** [comment]
Thank you @jurvis!

**Comment by marcosvafilho** [comment]
@speric version available on rubygems does not have this fix, could you update when you have the time? thanks :)

**Pull request merged**
